Repository puppetlabs/pdksync, pull requests merged in 2018-11, with the labels that each got.

#73 (MODULES-8181) - Release Prep for 0.2.0
  CHANGELOG.md
  pdksync.gemspec
Labels: maintenance

#75 (MODULES-7695) - Add maintenance labels for PRs
  README.md
  Rakefile
  lib/pdksync.rb
  lib/pdksync/constants.rb
  spec/lib/pdksync_spec.rb
Labels: feature

#76 (MODULES-8231) - Add additional title info for pdksync runs
  README.md
  Rakefile
  lib/pdksync.rb
Labels: feature

#77 (MODULES-7193) - Handle managed_modules when file is empty
  lib/pdksync.rb
Labels: maintenance

#78 (MODULES-7235) - Handle invalid/inaccessible GitHub repos
  lib/pdksync.rb
Labels: maintenance

#79 (MODULES-8002) - Fix bundle commands not running in correct dir
  lib/pdksync.rb
Labels: bugfix

#81 (MODULES-7233) - Add configurable file option
  README.md
  Rakefile
  lib/pdksync/constants.rb
Labels: feature
